---
title: "Assignment_3_rspake1"
output: html_document
---
## Set up for our model

```{r cars}
library(keras)
maxlen <- 150
training_samples <- 100
validation_samples <- 10000
max_features <- 10000

imdb <- dataset_imdb(num_words = max_features)
c(c(x_train, y_train), c(x_test, y_test)) %<-% imdb

Data = imdb$train$x
Labels = imdb$train$y

tokenizer <- text_tokenizer(num_words = max_features) %>% 
  fit_text_tokenizer(Data)
sequences <- texts_to_sequences(tokenizer, imdb$train)

word_index = tokenizer$word_index
cat("Found", length(word_index), "unique tokens.\n")

Data <- pad_sequences(sequences, maxlen = maxlen)
Labels = as.array(Labels)

cat("Shape of Data tesor:", dim(data), "\n")
cat('Shape of Label tensor:', dim(Labels), "\n")

Index <- sample(1:nrow(Data))
training_indices <- Index[1:training_samples]
validation_indices <- Index[(training_samples + 1):
                              (training_samples + validation_samples)]

x_train <- Data[training_indices,]
y_train <- Labels[training_indices]

x_val <- Data[validation_indices,]
y_val <- Labels[validation_indices]



```


```{r}
model1 <- keras_model_sequential() %>% 
  layer_embedding(input_dim = 10000, output_dim = 8,
                  input_length = maxlen) %>%
  layer_flatten() %>%
  layer_dense(units = 1, activation = "sigmoid")

model1 %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("acc")
)
history <- model1 %>% fit(
  x_train, y_train,
  epochs = 10,
  batch_size = 32,
  validation_data = list(x_test,y_test)
)
```


## Including Plots

You can also embed plots, for example:

```{r model}
library(keras)

max_features <- 10000
maxlen <- 150
batch_size <- 32
cat("Loading data...\n")
imdb <- dataset_imdb(num_words = max_features)
c(c(input_train, y_train), c(input_test,y_test)) %<-% imdb 
cat(length(input_train), "train sequences\n")
cat(length(input_test), "test seuences")

cat("Pad sequences (samples x times)\n")
input_train <- pad_sequences(input_train, maxlen = maxlen)
input_test <- pad_sequences(input_test, maxlen = maxlen)
cat("input_train shape:", dim(input_train), "\n")
cat("input_test shape:", dim(input_test), "\n")
```

```{r}

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
